version: "3"

services:
  yggdrasil:
    build: .
    container_name: yggdrasil
    restart: unless-stopped
    cap_add:
        - NET_ADMIN
    devices:
        - '/dev/net/tun'
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    ports:
      - "127.0.0.1:53:53/tcp"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:80:80/tcp"

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    depends_on: 
      - yggdrasil
    network_mode: service:yggdrasil
    environment:
      TZ: 'Europe/Moscow'
      WEBPASSWORD: 'my super secret password'
      PIHOLE_DNS_: '302:db60::53;300:6223::53;302:7991::53;301:23b4:991a:634d::53;94.16.114.254;81.169.136.222;9.9.9.11;9.9.9.9'
      DNSSEC: 'true'
      VIRTUAL_HOST: '127.0.0.1'
      WEBTHEME: 'default-darker'
        #    network_mode: host
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
