version: "3"

services:
  yggdrasil:
    build: ./yggdrasil/.
    container_name: yggdrasil
    restart: unless-stopped
    cap_add:
        - NET_ADMIN
    devices:
        - '/dev/net/tun'
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    ports:
      - "127.0.0.1:53:53/tcp"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:8080:80/tcp"
      - "[::1]:53:53/tcp"
      - "[::1]:53:53/udp"
      - "[::1]:8080:80/tcp"
    mac_address: 00:07:ef:66:66:66
    labels:
      - "com.centurylinklabs.watchtower.scope=pihole"

  dnscrypt:
    build: ./dnscrypt/.
    container_name: dnscrypt
    restart: unless-stopped
    network_mode: service:yggdrasil
    labels:
      - "com.centurylinklabs.watchtower.scope=pihole"

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    depends_on: 
      - yggdrasil
      - dnscrypt
    network_mode: service:yggdrasil
    environment:
      TZ: 'Europe/Moscow'
      WEBPASSWORD: 'my super secret password'
      PIHOLE_DNS_: 'yggdrasil#55;324:71e:281a:9ed3::53;200:2892:d0f:bc20:8a8e:c7be:9d9e:ab55;300:6223::53'
      DNSSEC: 'true'
      VIRTUAL_HOST: 'pi.hole'
      WEBTHEME: 'default-darker'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=pihole"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: --interval 30 --scope pihole
